{
 "title": "ftdc_dashboard",
 "time": { "from": "2024-05-25T19:23:09.607Z", "to": "2031-05-26T00:01:28.240Z" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values({__name__=~\"ftdc_.*\"}, hostname)"
    }
   },
   {
    "name": "version",
    "label": "version",
    "query": {
     "query": "label_values({__name__=~\"ftdc_.*\",hostname=~\"^(${hostname:pipe})$\"}, version)"
    }
   }
  ]
 },
 "panels": [
  { "title": "WiredTiger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WiredTiger Tickets",
   "type": "timeseries",
   "description": "Tickets Available Read displays the number of read tickets available to the WiredTiger storage engine. Read tickets represent the number of concurrent read operations allowed into the storage engine. When this value reaches zero, new read requests might queue until a read ticket becomes available.\n\nTickets Available Write displays the number of write tickets available to the WiredTiger storage engine. Write tickets represent the number of concurrent write operations allowed into the storage engine. When this value reaches zero, new write requests might queue until a write ticket becomes available.",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time({__name__=\"ftdc_serverStatus.wiredTiger.concurrentTransactions.write.available\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "serverStatus.wiredTiger.concurrentTransactions.write.available"
    },
    {
     "expr": "last_over_time({__name__=\"ftdc_serverStatus.wiredTiger.concurrentTransactions.read.available\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "serverStatus.wiredTiger.concurrentTransactions.read.available"
    }
   ]
  },
  {
   "title": "WiredTiger cache",
   "type": "timeseries",
   "description": "used displays the total bytes cached in memory for serving reads and writes.\n\nThese metrics include both indexes and data from the working set.\n\nSustained high cache usage indicates the RAM is too small for your workloads. Optimize your queries to avoid frequent disk reads. If write operations make cache usage high, throttle them.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(last_over_time({__name__=\"ftdc_serverStatus.wiredTiger.cache.maximum bytes configured\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])) * 9.31322574615e-10",
     "legendFormat": "serverStatus.wiredTiger.cache.maximum bytes configured"
    },
    {
     "expr": "(last_over_time({__name__=\"ftdc_serverStatus.wiredTiger.cache.bytes currently in the cache\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])) * 9.31322574615e-10",
     "legendFormat": "serverStatus.wiredTiger.cache.bytes currently in the cache"
    }
   ]
  },
  {
   "title": "Mb read into cache / written from cache",
   "type": "timeseries",
   "description": "read Into displays the rate in bytes per second of data read from disk into memory to service queries.\n\nwritten From  displays the rate in bytes per second of data written from memory into disk to service writes.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.wiredTiger.cache.bytes written from cache\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.wiredTiger.cache.bytes written from cache"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.wiredTiger.cache.bytes read into cache\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.wiredTiger.cache.bytes read into cache"
    }
   ]
  },
  {
   "title": "Pages Evicted",
   "type": "timeseries",
   "description": "Clean vs dirty data\n\nClean refers to data in the cache that is identical to the version stored on disk.\nDirty refers to data in the cache that has been modified and needs to be reconciled with the data stored on the disk.\n\nClean vs dirty eviction\n\nIn the case of clean eviction, there is no dirty content on the page and it is directly removed from the memory. After that, the page remains solely on the disk unchanged.\nIn the case of dirty eviction, the dirty page goes through reconciliation. The obsolete content on the page is thrown out, the latest value goes to the data store and older values go to the history store.",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.wiredTiger.cache.modified pages evicted\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.wiredTiger.cache.modified pages evicted"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.wiredTiger.cache.unmodified pages evicted\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.wiredTiger.cache.unmodified pages evicted"
    }
   ]
  },
  {
   "title": "Dirty mb in the cache",
   "type": "timeseries",
   "description": "indicates modified data that needs to be written to the data files via a checkpoint.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "last_over_time({__name__=\"ftdc_serverStatus.wiredTiger.cache.tracked dirty bytes in the cache\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "serverStatus.wiredTiger.cache.tracked dirty bytes in the cache"
    }
   ]
  },
  {
   "title": "Mb written for checkpoint",
   "type": "timeseries",
   "description": "A checkpoint is a known point in time from which WiredTiger can recover in the event of a crash or unexpected shutdown.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.wiredTiger.block-manager.bytes written for checkpoint\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.wiredTiger.block-manager.bytes written for checkpoint"
    }
   ]
  },
  {
   "title": "wiredTiger Block Manager",
   "type": "timeseries",
   "description": "The WiredTiger block manager subsystem manages the reading and writing of data from the disk. It is designed to facilitate high performance, economic use of disk space and customizability.",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.wiredTiger.block-manager.bytes read\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.wiredTiger.block-manager.bytes read"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.wiredTiger.block-manager.bytes written\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.wiredTiger.block-manager.bytes written"
    }
   ]
  },
  {
   "title": "WiredTiger Data Handle",
   "type": "timeseries",
   "description": "A WiredTiger Data Handle (dhandle) is a generic representation of any named data source. This representation contains information such as its name, how many references there are to it, individual data source statistics and what type of underlying data object it is.\n\nWiredTiger maintains all dhandles in a global dhandle list accessed from the connection. Multiple sessions access this list, which is protected by a R/W lock. Each session also maintains a session dhandle cache which is a cache of dhandles a session has operated upon. The entries in the cache are references into the global dhandle list.",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "expr": "last_over_time({__name__=\"ftdc_serverStatus.wiredTiger.data-handle.connection data handles currently active\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "serverStatus.wiredTiger.data-handle.connection data handles currently active"
    }
   ]
  },
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(quantile_over_time(0.5, {__name__=\"ftdc_serverStatus.mem.virtual\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])) * 0.001",
     "legendFormat": "serverStatus.mem.virtual"
    },
    {
     "expr": "(quantile_over_time(0.5, {__name__=\"ftdc_serverStatus.mem.resident\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])) * 0.001",
     "legendFormat": "serverStatus.mem.resident"
    }
   ]
  },
  {
   "title": "Page faults",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.extra_info.page_faults\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.extra_info.page_faults"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "expr": "last_over_time({__name__=\"ftdc_serverStatus.connections.active\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "serverStatus.connections.active"
    },
    {
     "expr": "last_over_time({__name__=\"ftdc_serverStatus.connections.current\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "serverStatus.connections.current"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.connections.totalCreated\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.connections.totalCreated"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opLatencies.reads.latency\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opLatencies.reads.latency"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opLatencies.writes.latency\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opLatencies.writes.latency"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opLatencies.commands.latency\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opLatencies.commands.latency"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opcounters.update\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opcounters.update"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opcounters.query\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opcounters.query"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opcounters.insert\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opcounters.insert"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opcounters.getmore\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opcounters.getmore"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opcounters.delete\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opcounters.delete"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opcounters.command\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opcounters.command"
    }
   ]
  },
  {
   "title": "Network requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 27 },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.network.numRequests\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.network.numRequests"
    }
   ]
  },
  {
   "title": "Current Queue writers / readers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time({__name__=\"ftdc_serverStatus.globalLock.currentQueue.writers\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "serverStatus.globalLock.currentQueue.writers"
    },
    {
     "expr": "last_over_time({__name__=\"ftdc_serverStatus.globalLock.currentQueue.readers\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "serverStatus.globalLock.currentQueue.readers"
    }
   ]
  },
  {
   "title": "Replica members health",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(last_over_time({__name__=~\"ftdc_replSetGetStatus\\\\.members\\\\.\\\\d+\\\\.health\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval]), \"member\", \"$1\", \"__name__\", \"ftdc_replSetGetStatus\\\\.members\\\\.(\\\\d+)\\\\.health\")",
     "legendFormat": "member {{member}} health"
    }
   ]
  },
  {
   "title": "Replica members lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "-1 * (label_replace(last_over_time({__name__=~\"ftdc_replSetGetStatus\\\\.members\\\\.\\\\d+\\\\.lastAppliedWallTime\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval]), \"member\", \"$1\", \"__name__\", \"ftdc_replSetGetStatus\\\\.members\\\\.(\\\\d+)\\\\.lastAppliedWallTime\") - on(hostname, version) group_left() last_over_time({__name__=\"ftdc_serverStatus.localTime\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval]))",
     "legendFormat": "member {{member}} lag"
    }
   ]
  },
  {
   "title": "Operations latencies op",
   "type": "timeseries",
   "description": "Operation latencies for the instance as a whole.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opLatencies.reads.ops\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opLatencies.reads.ops"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opLatencies.writes.ops\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opLatencies.writes.ops"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opLatencies.commands.ops\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opLatencies.commands.ops"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(last_over_time({__name__=\"ftdc_serverStatus.uptime\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])) / 86400",
     "legendFormat": "serverStatus.uptime (days)"
    }
   ]
  },
  {
   "title": "Replica members ping",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "last_over_time({__name__=~\"ftdc_replSetGetStatus\\\\.members\\\\.\\\\d+\\\\.pingMs\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "FlowControl isLagged",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.flowControl.isLaggedTimeMicros\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.flowControl.isLaggedTimeMicros"
    }
   ]
  },
  {
   "title": "Asserts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.asserts.warning\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.asserts.warning"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.asserts.user\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.asserts.user"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.asserts.rollovers\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.asserts.rollovers"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.asserts.regular\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.asserts.regular"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.asserts.msg\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.asserts.msg"
    }
   ]
  },
  {
   "title": "Query Executor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.metrics.queryExecutor.scannedObjects\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.metrics.queryExecutor.scannedObjects"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.metrics.queryExecutor.scanned\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.metrics.queryExecutor.scanned"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.metrics.queryExecutor.collectionScans.total\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.metrics.queryExecutor.collectionScans.total"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.metrics.commands.createIndexes.total\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.metrics.commands.createIndexes.total"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.metrics.commands.dataSize.total\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.metrics.commands.dataSize.total"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.metrics.commands.dropIndexes.total\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.metrics.commands.dropIndexes.total"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.metrics.commands.listCollections.total\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.metrics.commands.listCollections.total"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.metrics.commands.listDatabases.total\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.metrics.commands.listDatabases.total"
    }
   ]
  },
  {
   "title": "avg Obj Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 49 },
   "targets": [
    {
     "expr": "avg_over_time({__name__=\"ftdc_local.oplog.rs.stats.storageStats.avgObjSize\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "local.oplog.rs.stats.storageStats.avgObjSize"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 50 },
   "targets": [
    {
     "expr": "last_over_time({__name__=\"ftdc_serverStatus.metrics.cursor.open.noTimeout\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "serverStatus.metrics.cursor.open.noTimeout"
    },
    {
     "expr": "last_over_time({__name__=\"ftdc_serverStatus.metrics.cursor.open.pinned\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "serverStatus.metrics.cursor.open.pinned"
    },
    {
     "expr": "last_over_time({__name__=\"ftdc_serverStatus.metrics.cursor.open.total\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "serverStatus.metrics.cursor.open.total"
    },
    {
     "expr": "last_over_time({__name__=\"ftdc_serverStatus.metrics.cursor.timedOut\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "serverStatus.metrics.cursor.timedOut"
    }
   ]
  },
  {
   "title": "Documents (deleted / inserted / returned / updated)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.metrics.document.updated\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.metrics.document.updated"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.metrics.document.returned\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.metrics.document.returned"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.metrics.document.inserted\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.metrics.document.inserted"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.metrics.document.deleted\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.metrics.document.deleted"
    }
   ]
  },
  {
   "title": "Opcounters Replica",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 55 },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opcountersRepl.command\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opcountersRepl.command"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opcountersRepl.delete\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opcountersRepl.delete"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opcountersRepl.getmore\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opcountersRepl.getmore"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opcountersRepl.insert\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opcountersRepl.insert"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opcountersRepl.query\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opcountersRepl.query"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.opcountersRepl.update\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.opcountersRepl.update"
    }
   ]
  },
  {
   "title": "Query Targeting: Scanned Objects / Returned",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamp_min(deriv({__name__=\"ftdc_serverStatus.metrics.queryExecutor.scannedObjects\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]), 0) / clamp_min(clamp_min(deriv({__name__=\"ftdc_serverStatus.metrics.document.returned\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]), 0), 1)",
     "legendFormat": "scanned / returned"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Network In / Out physical",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.network.physicalBytesIn\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.network.physicalBytesIn"
    },
    {
     "expr": "deriv({__name__=\"ftdc_serverStatus.network.physicalBytesOut\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "serverStatus.network.physicalBytesOut"
    }
   ]
  },
  {
   "title": "Network In / Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "expr": "(deriv({__name__=\"ftdc_serverStatus.network.bytesOut\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])) * 9.53674316406e-07",
     "legendFormat": "serverStatus.network.bytesOut"
    },
    {
     "expr": "(deriv({__name__=\"ftdc_serverStatus.network.bytesIn\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])) * 9.53674316406e-07",
     "legendFormat": "serverStatus.network.bytesIn"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time({__name__=\"ftdc_local.oplog.rs.stats.storageStats.freeStorageSize\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "local.oplog.rs.stats.storageStats.freeStorageSize"
    },
    {
     "expr": "avg_over_time({__name__=\"ftdc_local.oplog.rs.stats.storageStats.storageSize\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "local.oplog.rs.stats.storageStats.storageSize"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate({__name__=\"ftdc_systemMetrics.cpu.user_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) / clamp_min((rate({__name__=\"ftdc_systemMetrics.cpu.idle_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.user_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.iowait_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.nice_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.softirq_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.steal_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.system_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])), 1e-9)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * rate({__name__=\"ftdc_systemMetrics.cpu.system_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) / clamp_min((rate({__name__=\"ftdc_systemMetrics.cpu.idle_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.user_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.iowait_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.nice_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.softirq_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.steal_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.system_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])), 1e-9)",
     "legendFormat": "system"
    },
    {
     "expr": "100 * rate({__name__=\"ftdc_systemMetrics.cpu.iowait_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) / clamp_min((rate({__name__=\"ftdc_systemMetrics.cpu.idle_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.user_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.iowait_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.nice_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.softirq_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.steal_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval]) + rate({__name__=\"ftdc_systemMetrics.cpu.system_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])), 1e-9)",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "Disk writes and reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
   "targets": [
    {
     "expr": "deriv(label_replace({__name__=~\"ftdc_systemMetrics[.]disks[.].*[.]writes\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"},\"device\",\"$1\",\"__name__\",\"ftdc_systemMetrics[.]disks[.]([^.]+)[.]writes\")[$__rate_interval])",
     "legendFormat": "{{device}} writes/s"
    },
    {
     "expr": "deriv(label_replace({__name__=~\"ftdc_systemMetrics[.]disks[.].*[.]reads\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"},\"device\",\"$1\",\"__name__\",\"ftdc_systemMetrics[.]disks[.]([^.]+)[.]reads\")[$__rate_interval])",
     "legendFormat": "{{device}} reads/s"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "avg_over_time({__name__=\"ftdc_systemMetrics.memory.MemAvailable_kb\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "systemMetrics.memory.MemAvailable_kb"
    },
    {
     "expr": "avg_over_time({__name__=\"ftdc_systemMetrics.memory.MemFree_kb\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "systemMetrics.memory.MemFree_kb"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "last_over_time(label_replace({__name__=~\"ftdc_systemMetrics[.]disks[.].*[.]io_in_progress\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"},\"device\",\"$1\",\"__name__\",\"ftdc_systemMetrics[.]disks[.]([^.]+)[.]io_in_progress\")[$__interval])",
     "legendFormat": "{{device}} io_in_progress"
    },
    {
     "expr": "deriv(label_replace({__name__=~\"ftdc_systemMetrics[.]disks[.].*[.]io_queued_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"},\"device\",\"$1\",\"__name__\",\"ftdc_systemMetrics[.]disks[.]([^.]+)[.]io_queued_ms\")[$__rate_interval])",
     "legendFormat": "{{device}} io_queued_ms/s"
    },
    {
     "expr": "deriv(label_replace({__name__=~\"ftdc_systemMetrics[.]disks[.].*[.]io_time_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"},\"device\",\"$1\",\"__name__\",\"ftdc_systemMetrics[.]disks[.]([^.]+)[.]io_time_ms\")[$__rate_interval])",
     "legendFormat": "{{device}} io_time_ms/s"
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "targets": [
    {
     "expr": "deriv(label_replace({__name__=~\"ftdc_systemMetrics[.]disks[.].*[.]write_sectors\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"},\"device\",\"$1\",\"__name__\",\"ftdc_systemMetrics[.]disks[.]([^.]+)[.]write_sectors\")[$__rate_interval])",
     "legendFormat": "{{device}} write_sectors/s"
    },
    {
     "expr": "deriv(label_replace({__name__=~\"ftdc_systemMetrics[.]disks[.].*[.]write_time_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"},\"device\",\"$1\",\"__name__\",\"ftdc_systemMetrics[.]disks[.]([^.]+)[.]write_time_ms\")[$__rate_interval])",
     "legendFormat": "{{device}} write_time_ms/s"
    },
    {
     "expr": "deriv(label_replace({__name__=~\"ftdc_systemMetrics[.]disks[.].*[.]writes_merged\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"},\"device\",\"$1\",\"__name__\",\"ftdc_systemMetrics[.]disks[.]([^.]+)[.]writes_merged\")[$__rate_interval])",
     "legendFormat": "{{device}} writes_merged/s"
    }
   ]
  },
  {
   "title": "Swap Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "targets": [
    {
     "expr": "avg_over_time({__name__=\"ftdc_systemMetrics.memory.SwapFree_kb\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "systemMetrics.memory.SwapFree_kb"
    },
    {
     "expr": "avg_over_time({__name__=\"ftdc_systemMetrics.memory.SwapTotal_kb\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__interval])",
     "legendFormat": "systemMetrics.memory.SwapTotal_kb"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "deriv(label_replace({__name__=~\"ftdc_systemMetrics[.]disks[.].*[.]read_sectors\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"},\"device\",\"$1\",\"__name__\",\"ftdc_systemMetrics[.]disks[.]([^.]+)[.]read_sectors\")[$__rate_interval])",
     "legendFormat": "{{device}} read_sectors/s"
    },
    {
     "expr": "deriv(label_replace({__name__=~\"ftdc_systemMetrics[.]disks[.].*[.]read_time_ms\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"},\"device\",\"$1\",\"__name__\",\"ftdc_systemMetrics[.]disks[.]([^.]+)[.]read_time_ms\")[$__rate_interval])",
     "legendFormat": "{{device}} read_time_ms/s"
    },
    {
     "expr": "deriv(label_replace({__name__=~\"ftdc_systemMetrics[.]disks[.].*[.]reads_merged\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"},\"device\",\"$1\",\"__name__\",\"ftdc_systemMetrics[.]disks[.]([^.]+)[.]reads_merged\")[$__rate_interval])",
     "legendFormat": "{{device}} reads_merged/s"
    }
   ]
  },
  {
   "title": "TCP ActiveOpens / AttemptFails / EstabResets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Tcp:ActiveOpens\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Tcp:ActiveOpens"
    },
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Tcp:AttemptFails\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Tcp:AttemptFails"
    },
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Tcp:EstabResets\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Tcp:EstabResets"
    }
   ]
  },
  {
   "title": "TCP: InSegs / OutSegs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Tcp:InSegs\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Tcp:InSegs"
    },
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Tcp:OutSegs\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Tcp:OutSegs"
    }
   ]
  },
  {
   "title": "TCP Routing Issues",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Ip:OutNoRoutes\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Ip:OutNoRoutes"
    }
   ]
  },
  {
   "title": "TCP Connection Issues",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Tcp:CurrEstab\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Tcp:CurrEstab"
    },
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Tcp:EstabResets\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Tcp:EstabResets"
    },
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Tcp:OutRsts\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Tcp:OutRsts"
    }
   ]
  },
  {
   "title": "TCP Packet Loss or Corruption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Tcp:InCsumErrors\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Tcp:InCsumErrors"
    },
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Tcp:InErrs\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Tcp:InErrs"
    },
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Tcp:RetransSegs\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Tcp:RetransSegs"
    },
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Ip:InDiscards\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Ip:InDiscards"
    },
    {
     "expr": "deriv({__name__=\"ftdc_systemMetrics.netstat.Ip:OutDiscards\", hostname=~\"^(${hostname:pipe})$\", version=~\"^(${version:pipe})$\"}[$__rate_interval])",
     "legendFormat": "systemMetrics.netstat.Ip:OutDiscards"
    }
   ]
  }
 ]
}